version: '3.3'

services:
  
  api:
    build: 
      context: ./api
    command: npm start
    restart: unless-stopped
    container_name: game-project
    ports: 
      - 80:3000
    volumes: 
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
  mongo:
    image: mongo
    container_name: game-mongo
    volumes:
      - ./mongo-data/game-project:/data/db
    ports:
      - 27018:27017

                
